[package]
name = "jsonrpc"
version = "1.0.4"
description = "Generated types based on the JSON-Schema for jsonrpc"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0"
derive_builder = "0.10"

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]
